gamemodes/commands/cmd/napraw.pwn
gamemodes/commands/cmd/tankowanie.pwn

naprawa 800 tankowanie 300

---

gamemodes/commands/cmd/sluzba.pwn

duty przy windzie fbi

---

gamemodes/commands/cmd/aresztuj.pwn
gamemodes/modules/oferty/commands/akceptuj/akceptuj_impl.pwn

lider fbi zglosil mi ze nie leci mu kasa do sejfu za aresztowania i mandaty. ten pr powinien to naprawic

fix sejfy za areszt i mandat

---

gamemodes/commands/cmd/pr.pwn
gamemodes/system/funkcje.pwn

Prawdopodobnie spawny nie zapisywały się bo zapis organizacji w MySQL następował tylko podczas OnGamemodeExit, a serwer częściej się crashował niż wyłączał poprawnie. Dodałem orgSave() w /pr

fix /pr spawn

---

db/mrp_samp.sql
gamemodes/commands/cmd/licencje.pwn
gamemodes/modules/fishing/commands/lowienie/lowienie_impl.pwn
gamemodes/modules/fishing/fishing.pwn
gamemodes/mysql/mru_mysql.pwn
gamemodes/system/funkcje.pwn
gamemodes/system/timery.pwn

Poprawki do najważniejszego systemu na serwerze czyli łowienia ryb
[188cd2d](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/188cd2db913e663c35e453a23e5fcc17d2c21d46) [bde6d65](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/bde6d65f654d1cbd335eaa7183a8ebd9b6b23374) - nadanie 1wl nielegalnym wędkarzom którzy mają 0wl
[1024d04](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/1024d04f4b64759538ff852eda410a085989d7da) - poprawa literowki istniejacej w /licencje (Karta wędkarskia)
[1e103ae](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/1e103aee4052ff4c4a1c83819c645b66038efce5) - zapisywanie ryb w bazie zeby nie znikaly po /q lub crashu (backport na podstawie skryptu kotnika)
[4715632](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/4715632d038267161d3d1fc7cbe759d543cad4fe) - …

Poprawki do ryb

---

gamemodes/Mrucznik-RP.pwn
gamemodes/commands/cmd/rozwiaz.pwn
gamemodes/commands/cmd/zablokujw.pwn
gamemodes/modules/weryfikacje/weryfikacje.pwn
gamemodes/old_modules/niceczlowiek/wybieralka.pwn
pawn.json

4772f07759acb6834c9bd5b5371674b160614bef - przetestowane na windows, serwer odpala na 0.3.DL i plugin się wczytuje bez problemu, integracja z sampctl wzorowa. Potrzebuje testu na środowisku produkcji, czy nie ma problemów na innym systemie.
Nex-AC może sprawdzać pakiety wysyłane/odbierane przez gracza, ten plugin umożliwia uruchomienie tej funkcji. Powinno to pomóc na crashe przez spamienie client-side funkcji VehicleDestroyComponent oraz pomóc przy teleporcie aut do wyznaczonego miejsca na skybox; Na pewno wydajniejsza opcja niż defaultowe rozwiązania na timery i pętle.
Reszta commitów to drobne, pojedyńcze poprawki. Lockdown od teraz wymusza VW także podczas tutorialu.

Poprawki do systemu zabezpieczeń, poprawki @cmd

---

gamemodes/modules/antycheat/antycheat.pwn

Poprawki do antyczita na kłębienie pojazdów.

Poprawki do antyczita na kłębienie pojazdów

---

gamemodes/Mrucznik-RP.pwn
gamemodes/modules/antycheat/antycheat.pwn
gamemodes/system/funkcje.pwn

Dodanie funkcji umożliwiającej wykrywanie nachodzenia na siebie pojazdów. Wprowadzenie jej jako kryterium wykrywania lagowania pojazdami w antyczicie. Drobne bugfixy do antyczita.

Antyczit na kłębienie pojazdów - usprawnienie

---

gamemodes/system/funkcje.pwn

https://github.com/MrucznikRolePlay/Mrucznik-RP-gamemode/issues/406

Poprawka demorgan

---

gamemodes/commands/cmd/ah.pwn
gamemodes/commands/cmd/kajdanki.pwn
gamemodes/commands/cmd/pomoc2.pwn
gamemodes/modules/choroby/commands/aulecz/aulecz_impl.pwn
gamemodes/modules/napady/napady.pwn

Kajdanki na LSPD na slużbie tylko jako FBI, FBI nie może na sobie dawać (nie tyczy się to liderów)

Last-minute zmiany 

---

gamemodes/commands/cmd/sprzedajzestaw.pwn
gamemodes/dialogs/OnDialogResponse.pwn
gamemodes/modules/oferty/commands/akceptuj/akceptuj_impl.pwn
gamemodes/system/definicje.pwn
gamemodes/system/zmienne.pwn

https://github.com/MrucznikRolePlay/Mrucznik-RP-gamemode/issues/380

Sprzedawanie zestawu akceptowane komendą /sprzedajzestaw

---

gamemodes/Mrucznik-RP.pwn
gamemodes/commands/cmd/pr.pwn
gamemodes/commands/cmd/qf.pwn
gamemodes/dialogs/OnDialogResponse.pwn
gamemodes/mysql/mru_mysql.pwn
gamemodes/system/definicje.pwn
gamemodes/system/funkcje.pwn
gamemodes/system/zmienne.pwn

dodaje rodzinom mozliwosc zarzadzania pracownikami ktorzy sa offline. obecnie trzeba czekac az czlonek wejdzie do gry aby mozna go bylo zwolnic, zmienic range itp.
wiekszosc funkcjonalnosci przerobiona z /fpanel
includes: [Mrucznik-RP-Includes#9](https://github.com/MrucznikRolePlay/Mrucznik-RP-Includes/pull/9)

panel pracownikow dla rodzin

---

gamemodes/commands/cmd/poddajsie.pwn
gamemodes/modules/oferty/commands/akceptuj/akceptuj_impl.pwn

+ Poprawiono komunikat przy akceptacji sexu o dodanej ilości HP
+ Poprawiono ucinanie komunikatu łowców nagród przy /poddajsie, o tym jaką komendę użyć by się poddać.

Mini-bugfixy

---

gamemodes/Mrucznik-RP.pwn
gamemodes/mysql/mru_mysql.pwn

VW się nie zapisywało, dodać kolumnę do bazy
ALTER TABLE `mru_konta` ADD COLUMN `VW` int(11) NOT NULL DEFAULT '0' AFTER `pHealth`

naprawa przywracania pozycji i komunikatów przy wsiadaniu do autek jako pasażer

---

gamemodes/commands/cmd/panelvinyl.pwn
gamemodes/dialogs/OnDialogResponse.pwn

zmiana nazw napojów już działa

fixy /panelvinyl (issue)

---

gamemodes/commands/cmd/zaparkuj.pwn
gamemodes/modules/pojazdy/commands/lidercar/lidercar_impl.pwn

nie jestem pewny czy `if(strcmp(akcja, "", true) != 0)` zadziała tak jak powinno. (if na: `czy akcja[16] nie jest pusta`)

Logi do /lidercar, /zaparkuj

---

gamemodes/Mrucznik-RP.pwn
gamemodes/commands/cmd/pomoc2.pwn
gamemodes/dialogs/OnDialogResponse.pwn
gamemodes/modules/admin/admin.pwn
gamemodes/modules/komendy/commands/komendy_commands.pwn
gamemodes/modules/komendy/commands/opis/opis_impl.pwn
gamemodes/modules/komendy/commands/togopis/command.json
gamemodes/modules/komendy/commands/togopis/togopis.pwn
gamemodes/modules/komendy/commands/togopis/togopis_impl.pwn
gamemodes/modules/komendy/commands/togvopis/command.json
gamemodes/modules/komendy/commands/togvopis/togvopis.pwn
gamemodes/modules/komendy/commands/togvopis/togvopis_impl.pwn
gamemodes/modules/pojazdy/pojazdy.pwn
gamemodes/old_modules/niceczlowiek/noysi.pwn
gamemodes/system/funkcje.pwn
gamemodes/system/zmienne.pwn

- Dodanie komendy /togopis.
- Dodanie informacji na temat /togopis i /togvopis do /pomoc.
- Naprawa buga - opisów pojazdów nie widać już przez ściany.
- Zmniejszenie niepotrzebnie dużego dystansu streamowania opisów graczy i pojazdów.

Dodano komendy /togopis i /togvopis

---

gamemodes/dialogs/OnDialogResponse.pwn
gamemodes/system/funkcje.pwn

Bugfix w /ub - AC czasami kickował. Dodatkowo kosmetyczne poprawki do kodu.

Poprawki do komendy /ub

---

gamemodes/system/timery.pwn

Frakcyjne naprawy i tankowania - poprawka komunikatów i nieścisłości.

Naprawy i tankowania zmiany

---

gamemodes/modules/pojazdy/pojazdy.pwn
gamemodes/modules/pojazdy/pojazdy_callbacks.pwn

Naprawa dublowania aut na kluczykach i odblokowanie /autok

---

gamemodes/commands/cmd/wezportfel.pwn

okradanie tylko osob w org przestepczej

fix wezportfel

---

gamemodes/commands/cmd/makeleader.pwn
gamemodes/commands/cmd/makemember.pwn
gamemodes/commands/cmd/makevlider.pwn
gamemodes/commands/cmd/przyjmij.pwn
gamemodes/commands/cmd/sluzba.pwn
gamemodes/system/funkcje.pwn

blokada /duty gdy nie ma sie ustawionego uniformu, powinno naprawic reporterow sn w skinie cj (powinno)

blokada duty bez uniformu

---

gamemodes/Mrucznik-RP.pwn
gamemodes/VERSION.pwn
gamemodes/modules/discord/discord.hwn
gamemodes/modules/discord/discord.pwn
gamemodes/system/funkcje.pwn
pawn.json

- Skompilowana wersja pluginu discord z zależnościami kompatybilnymi z innymi pluginami i systemem
- Info o włączeniu/wyłączeniu serwera
- Info o dołączeniu/wyjściu z serwera przez graczy

Discord update

---

gamemodes/modules/front_business/front_business.pwn
gamemodes/modules/frontbiz_gunshop/commands/sellkontrabandabot/sellkontrabandabot_impl.pwn
gamemodes/modules/frontbiz_gunshop/commands/sprzedajmatsbot/sprzedajmatsbot_impl.pwn
gamemodes/modules/frontbiz_gunshop/frontbiz_gunshop.pwn
gamemodes/modules/frontbiz_gunshop/frontbiz_gunshop_callbacks.pwn
gamemodes/modules/gangzone/gangzone.pwn
gamemodes/modules/organizacje/organizacje.pwn

Fix gspanel
